### ISSUE TITLE
Some broken links on doc.perl6.org

### ISSUE THREAD

**Issue by kjkuan** [perl6/doc#2777]
## The problem

I noticed a couple broken links on the doc website.

Under https://doc.perl6.org/:
- The  [Chat with us](https://docs.perl6.org/webchat.html) link
- The [Examples](https://docs.perl6.org/examples.html) link

Under https://perl6.org/community/:
- The [#perl6, our IRC channel](https://perl6.org/community/irc) link

The link to the `gather` statement under https://docs.perl6.org/language/list#List_assignment_context
is also broken.

**Comment by lizmat** [comment]
Fixed gather link with 499e3a297ff1886588

**Comment by JJ** [comment]
Since we're apparently serving now directly with Mojolicious, .htaccess is not working. I don't know if I should fix this by putting some server in front of mojolicious (as was the case before) or just simply change those URLs. I have no idea why these redirections were used.

**Comment by JJ** [comment]
Well, it was probably easier to redirect URL than fix the template or the place where it's generated. I'll have to dig up that.

**Comment by JJ** [comment]
Well, well, well. This is generated directly in htmlify.p6, of which not much more than #1823 needs to be said. TL;DR: it's going to be hard.

**Comment by kjkuan** [comment]
The example link (now just returns https://docs.perl6.org/) and the IRC link(still shows 'not found') are still not fixed. The IRC link is under perl6.org/community so that's probably not part of the docs site. Further more, the SSL/TLS certificate of https://docs.perl6.org has expired....

**Comment by JJ** [comment]
@kjkuan they should be fixed. Did you refresh the cache?

**Comment by JJ** [comment]
Ah, OK, I see. The problem is doc.perl6.org, not docs.perl6.org. That's not an official URL, and to tell you the truth, not one I knew existed. But well, it's there, so it'll have to be fixed.

**Comment by JJ** [comment]
Checking doc.perl6.org and docs.perl6.org they seem to be pointing to where they should point. The problem is that examples.perl6.org has not been brought back in the provisional infrastructure, but the chat link is where it should be (where it was before).

**Comment by kjkuan** [comment]
https://perl6.org/community/irc   is still broken

**Comment by JJ** [comment]
@kjkuan That's in another repo; it's better if you create an issue there... https://github.com/perl6/perl6.org

**Comment by kjkuan** [comment]
I just did. thanks.
